\set ON_ERROR_STOP on
begin;
delete from public.notification_reads where notification_id::text like 'd8000000-%';
delete from public.notifications where id::text like 'd8000000-%';
delete from public.journal_entries where id::text like 'd7400000-%';
delete from public.expenses where id::text like 'd7200000-%';
delete from public.journal_transactions where id::text like 'd7300000-%';
delete from public.accounting_periods where id::text like 'd7100000-%';
delete from public.financial_accounts where id::text like 'd7000000-%';
delete from public.inventory_movements where id::text like 'd6000000-%';
delete from public.sale_return_allocations where id::text like 'd5600000-%';
delete from public.sale_return_lines where id::text like 'd5500000-%';
delete from public.sale_returns where id::text like 'd5400000-%';
delete from public.sale_payments where id::text like 'd5300000-%';
delete from public.sale_lot_allocations where id::text like 'd5200000-%';
delete from public.sale_lines where id::text like 'd5100000-%';
delete from public.sales where id::text like 'd5000000-%';
delete from public.inventory_lots where id::text like 'd4000000-%';
delete from public.purchase_receipt_lines where id::text like 'd3400000-%';
delete from public.purchase_receipts where id::text like 'd3300000-%';
delete from public.purchase_bill_lines where id::text like 'd3200000-%';
delete from public.purchase_bills where id::text like 'd3100000-%';
delete from public.vendors where id::text like 'd3000000-%';
delete from public.products where id::text like 'd2000000-%';
delete from public.shop_memberships where user_id::text like 'd0000000-%';
delete from public.user_profiles where user_id::text like 'd0000000-%';
delete from auth.users where id::text like 'd0000000-%';
delete from public.shops where id::text like 'd1000000-%';
set constraints all immediate;
commit;
