package com.gdad.bags.ui.sale
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import com.gdad.bags.domain.model.*
import com.gdad.bags.domain.product.CatalogProduct
import com.gdad.bags.domain.sale.*
import com.gdad.bags.ui.components.ContentStateHost
import java.time.LocalDate
@Composable fun SaleCheckoutScreen(session:UserSession,state:SaleUiState,onRefresh:()->Unit,onPost:(SaleDraft)->Unit,onDismiss:()->Unit){ContentStateHost(state.content,onRefresh){products->SaleForm(session,products,state.isPosting,onPost)};state.safeMessage?.let{Text(it,Modifier.padding(16.dp),color=MaterialTheme.colorScheme.primary)};state.posted?.let{sale->AlertDialog(onDismissRequest=onDismiss,title={Text("Sale posted")},text={Column{Text("Server-authoritative FIFO receipt");Text("Total ${money(sale.grandTotalPaisa)}");Text("Paid ${money(sale.paidPaisa)}");Text("Due ${money(sale.duePaisa)}");if(session.role==UserRole.OWNER)sale.costTotalPaisa?.let{Text("FIFO cost ${money(it)}")};Text("${sale.lineCount} line(s) • ${sale.allocationCount} FIFO allocation(s)");Text("Sale ${sale.saleId}")}},confirmButton={Button(onClick=onDismiss){Text("Done")}})}}
@Composable private fun SaleForm(session:UserSession,products:List<CatalogProduct>,posting:Boolean,onPost:(SaleDraft)->Unit){val quantities=remember{mutableStateMapOf<String,String>()};val prices=remember{mutableStateMapOf<String,String>()};var date by remember{mutableStateOf(LocalDate.now().toString())};var discount by remember{mutableStateOf("")};var payment by remember{mutableStateOf("")};var method by remember{mutableStateOf(SalePaymentMethod.CASH)};var credit by remember{mutableStateOf(false)};var customer by remember{mutableStateOf("")};var contact by remember{mutableStateOf("")};var dueDate by remember{mutableStateOf(LocalDate.now().toString())};val lines=products.mapNotNull{p->val q=quantities[p.id]?.toIntOrNull()?:0;if(q>0)SaleLineDraft(p.id,p.name,q,if(session.role==UserRole.OWNER)prices[p.id]?.toDoubleOrNull()?.times(100)?.toLong() else null)else null};val localTotal=lines.sumOf{line->val p=products.single{it.id==line.productId};line.quantity.toLong()*(line.effectiveUnitPricePaisa?:p.sellingPricePaisa)}-(discount.toDoubleOrNull()?.times(100)?.toLong()?:0);val paid=payment.toDoubleOrNull()?.times(100)?.toLong()?:0;val valid=lines.isNotEmpty()&&lines.all{it.quantity<=products.single{p->p.id==it.productId}.quantityOnHand}&&localTotal>=0&&if(session.role==UserRole.SALESMAN)paid==localTotal else if(credit)paid<=localTotal&&customer.isNotBlank()&&contact.isNotBlank() else paid==localTotal
Column(Modifier.padding(16.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("New sale",style=MaterialTheme.typography.headlineSmall);OutlinedTextField(date,{date=it},label={Text("Business date YYYY-MM-DD")});products.forEach{p->Text("${p.name} • ${p.quantityOnHand} available • ${money(p.sellingPricePaisa)}");Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){OutlinedTextField(quantities[p.id].orEmpty(),{quantities[p.id]=it.filter(Char::isDigit)},label={Text("Qty")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Number),modifier=Modifier.weight(1f));if(session.role==UserRole.OWNER)OutlinedTextField(prices[p.id].orEmpty(),{prices[p.id]=it.filter{c->c.isDigit()||c=='.'}},label={Text("Override price")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Decimal),modifier=Modifier.weight(1f))}};if(session.role==UserRole.OWNER){OutlinedTextField(discount,{discount=it.filter{c->c.isDigit()||c=='.'}},label={Text("Sale discount")});TextButton(onClick={credit=!credit}){Text(if(credit)"Credit sale selected" else "Make credit sale")};if(credit){OutlinedTextField(customer,{customer=it},label={Text("Customer name")});OutlinedTextField(contact,{contact=it},label={Text("Customer contact")});OutlinedTextField(dueDate,{dueDate=it},label={Text("Due date YYYY-MM-DD")})}};Text("Review estimate ${money(localTotal.coerceAtLeast(0))}; server total is final.");OutlinedTextField(payment,{payment=it.filter{c->c.isDigit()||c=='.'}},label={Text(if(credit)"Payment now" else "Full payment")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Decimal));Row{TextButton(onClick={method=SalePaymentMethod.CASH}){Text(if(method==SalePaymentMethod.CASH)"Selected: Cash" else "Cash")};TextButton(onClick={method=SalePaymentMethod.BANK}){Text(if(method==SalePaymentMethod.BANK)"Selected: Bank" else "Bank")}};Button(enabled=valid&&!posting,onClick={onPost(SaleDraft(date,lines,(discount.toDoubleOrNull()?.times(100)?.toLong()?:0),credit,customer.trim().ifEmpty{null},contact.trim().ifEmpty{null},dueDate.takeIf{credit},if(paid>0)listOf(SalePaymentDraft(method,paid))else emptyList()))}){Text(if(posting)"Posting…" else "Confirm and post once")}}
}
private fun money(paisa:Long)="Rs %.2f".format(paisa/100.0)
